package seedu.nova.model.event;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.FormatStyle;

import seedu.nova.model.plan.Task;
import seedu.nova.model.plan.TaskFreq;
import seedu.nova.model.util.time.duration.DateTimeDuration;

/**
 * Event generated by task
 */
public class WeakEvent extends Event {
    private Task origin;

    public WeakEvent(String name, DateTimeDuration dtd, Task origin) {
        super(name, null, dtd.getStartTime(), dtd.getEndTime(), dtd.getStartDate());
        this.origin = origin;
    }

    public Task getOriginTask() {
        return origin;
    }

    /**
     * Sets date.
     *
     * @param date the date
     */
    @Override
    public void setDate(LocalDate date) {
        origin.deleteEvent(this);
        this.date = date;
        origin.addEvent(this);
    }

    @Override
    public String toString() {
        return "Description: " + desc + "\n"
                + "Venue: " + venue + "\n"
                + "Time: " + getDayOfWeek() + ", "
                + startTime.format(DateTimeFormatter.ofLocalizedTime(FormatStyle.SHORT))
                + " - " + endTime.format(DateTimeFormatter.ofLocalizedTime(FormatStyle.SHORT));
    }

    @Override
    public boolean equals(Object o) {
        if (o instanceof WeakEvent) {
            if (origin.getTaskFreq() == TaskFreq.WEEKLY) {
                return getDayOfWeek().equals(((WeakEvent) o).getDayOfWeek())
                        && getStartTime().equals(((WeakEvent) o).getStartTime())
                        && getEndTime().equals(((WeakEvent) o).getEndTime());
            } else {
                return getDate().equals(((WeakEvent) o).getDate())
                        && getStartTime().equals(((WeakEvent) o).getStartTime())
                        && getEndTime().equals(((WeakEvent) o).getEndTime());
            }
        } else {
            return super.equals(o);
        }
    }
}
