@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

Interface Storage <<Interface>>
Interface UserPrefsStorage <<Interface>>
Interface NovaStorage <<Interface>>

Class StorageManager
Class JsonUserPrefsStorage
Class JsonNovaStorage
Class JsonUtil
Class JsonSerializableNova

StorageManager .up.|> Storage
StorageManager o-right-> UserPrefsStorage
StorageManager o-left-> NovaStorage

JsonUserPrefsStorage .up.|>UserPrefsStorage
JsonUserPrefsStorage -left- JsonUtil: uses >
JsonNovaStorage .up.|> NovaStorage
JsonNovaStorage -right- JsonUtil: uses >
JsonNovaStorage .down.> JsonSerializableNova


JsonSerializableNova o-right-> JsonAdaptedPerson
JsonSerializableNova o-right-> JsonAdaptedPtTask
JsonSerializableNova o-down-> JsonAdaptedPlannerTask
JsonAdaptedPlannerTask o-right-> JsonAdaptedEvent
JsonSerializableNova o-down-> JsonAdaptedEvent
JsonAdaptedPerson o-right-> JsonAdaptedTag
@enduml
