@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":LogicParser" as LogicParser LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":AbUndoCommandParser" as AbUndoCommandParser LOGIC_COLOR
participant "u:AbUndoCommand" as AbUndoCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":Mode" as Mode MODEL_COLOR
participant ":VersionedAddressBook" as VersionedAddressBook MODEL_COLOR
end box

[-> LogicManager : execute("undo")
activate LogicManager

LogicManager -> LogicParser : parseCommand("undo")
activate LogicParser

LogicParser -> Model : getMode()
activate Model

Model --> LogicParser : mode
deactivate Model

LogicParser -> Mode : getModeEnum()
activate Mode

Mode --> LogicParser : mode
deactivate Mode

LogicParser -> AddressBookParser : parseCommand("undo")
activate AddressBookParser

create AbUndoCommandParser
AddressBookParser -> AbUndoCommandParser
activate AbUndoCommandParser

AbUndoCommandParser --> AddressBookParser
deactivate AbUndoCommandParser

AddressBookParser -> AbUndoCommandParser : parse("undo")
activate AbUndoCommandParser

create AbUndoCommand
AbUndoCommandParser -> AbUndoCommand
activate AbUndoCommand

AbUndoCommand --> AbUndoCommandParser : u
deactivate AbUndoCommand

AbUndoCommandParser --> AddressBookParser : u
deactivate AbUndoCommandParser
AbUndoCommandParser -[hidden]-> LogicManager : u
destroy AbUndoCommandParser

AddressBookParser --> LogicParser : u
deactivate AddressBookParser

LogicParser --> LogicManager : u
deactivate LogicParser

LogicManager -> AbUndoCommand : execute()
activate AbUndoCommand

AbUndoCommand -> Model : undoAddressBook()
activate Model

Model -> VersionedAddressBook : undo()
activate VersionedAddressBook

VersionedAddressBook -> VersionedAddressBook :resetData(ReadOnlyAddressBook)
VersionedAddressBook --> Model :
deactivate VersionedAddressBook

Model --> AbUndoCommand
deactivate Model

create CommandResult
AbUndoCommand -> CommandResult
activate CommandResult

CommandResult --> AbUndoCommand
deactivate CommandResult

AbUndoCommand --> LogicManager : result
deactivate AbUndoCommand
AbUndoCommand -[hidden]-> LogicManager : result
destroy AbUndoCommand

[<--LogicManager
deactivate LogicManager
@enduml
