package seedu.nova.model.schedule.event;

import java.time.LocalDate;

import seedu.nova.model.plan.Task;
import seedu.nova.model.util.time.duration.DateTimeDuration;

/**
 * Event generated by task
 */
public class WeakEvent extends Event {
    private Task origin;

    public WeakEvent(String name, DateTimeDuration dtd, Task origin) {
        super(name, null, dtd.getStartTime(), dtd.getEndTime(), dtd.getStartDate());
        this.origin = origin;
    }

    public Task getOriginTask() {
        return origin;
    }

    /**
     * Sets date.
     *
     * @param date the date
     */
    @Override
    public void setDate(LocalDate date) {
        origin.deleteEvent(this);
        this.date = date;
        origin.addEvent(this);
    }
}
